github-auth
code100x/cms pull request #1061
Opened 2024-08-27 22:39 UTC by Ashutoshpadhi629

### PR Fixes:
- updated github Oauth 
- fixed Calendar UI

Resolves #1057 #1056 

https://github.com/user-attachments/assets/f9ea8677-64f2-47f1-9af6-74d06011557e

https://github.com/user-attachments/assets/921b58d9-1f98-4ceb-8796-a735d97ec240

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

2024-08-27 22:43 UTC, devsargam commented
Few questions, for example if a user logged in with github then how does it log into website to access the course dashboard?

2024-08-27 22:44 UTC, devsargam commented
Also, @hkirat is this feature to be included in cms? or can we add this to some other place where we just aggregate the data to notion file

2024-08-27 22:47 UTC, Ashutoshpadhi629 commented
> Few questions, for example if a user logged in with github then how does it log into website to access the course dashboard?

no , the next Auth config is not changed , this github Oauth flow is completely different from that.

2024-08-27 22:49 UTC, devsargam requested changes

2024-08-27 22:49 UTC, devsargam commented on prisma/schema.prisma
>    content         CourseContent[]
This file has a lot of noise.

2024-08-27 22:49 UTC, devsargam commented on src/actions/payoutMethods/index.ts
> +    throw new Error('Unauthorized');
Don't directly throw an error. Just send 401 status code with "Unauthenticated" message

2024-08-27 22:49 UTC, devsargam commented on src/actions/payoutMethods/index.ts
> +    throw new Error('Unauthorized');
Save as above

2024-08-27 22:50 UTC, devsargam commented
@Ashutoshpadhi629 here are a few follow ups. Mention me again when u resolve all 3 for re-review

2024-09-01 12:10 UTC, devsargam commented
Closing in favour of https://github.com/code100x/cms/pull/1066

2024-09-01 12:10 UTC, closed without merging