Admin UI revamped + Discord notification (right from admin panel)
code100x/cms pull request #1181
Opened 2024-09-10 20:49 UTC by amanbairagi30

### PR Fixes:
- 1 Admin UI revamped
- 2 Discord notification (right from admin panel)

Resolves #116

#Discord Notification: 

https://github.com/user-attachments/assets/e165b98b-8f3c-4205-b9a6-631ca5369a70

![image](https://github.com/user-attachments/assets/2d953a78-dd3e-4b60-9cb6-a2dd836f0cc0)
![image](https://github.com/user-attachments/assets/5b0b8aca-50ae-4177-8f6f-3f08713887f3)
![image](https://github.com/user-attachments/assets/ed8fd00d-3f45-454f-aa34-3cd82ad08384)
![image](https://github.com/user-attachments/assets/b3d39846-92a8-4ea9-be4f-99cdcc126892)
![image](https://github.com/user-attachments/assets/0c980fa1-3c61-444f-8bf0-a768459be86f)

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

2024-09-10 20:49 UTC, amanbairagi30 commented
@hkirat @devsargam

2024-09-10 20:51 UTC, devsargam commented
Will check within this week. Thanks :)

2024-09-12 20:32 UTC, devsargam approved these changes

2024-09-12 20:32 UTC, devsargam commented
Checking locally

2024-09-12 21:11 UTC, devsargam requested changes

2024-09-12 21:11 UTC, devsargam commented on src/app/api/admin/content/route.ts
> +    content: 'Hello @everyone',
Should not tag everyone

2024-09-12 21:11 UTC, devsargam commented on src/app/api/admin/content/route.ts
> +    content: 'Hello @everyone',
```suggestion
    content: 'Hello everyone',
```

2024-09-12 21:14 UTC, merged

2024-09-12 21:14 UTC, devsargam commented
Thank u sir @amanbairagi30