add feature to search with Ctrl + k
code100x/cms pull request #1205
Opened 2024-09-12 11:27 UTC by AuenKr

### PR Fixes:
- Added Ctrl + K to the search box

Before:
https://github.com/user-attachments/assets/52422b91-9434-496a-89b9-a3f5bcc7af95

After:
https://github.com/user-attachments/assets/b185088e-abed-4e27-9b30-2673c3062d99

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

2024-09-12 11:45 UTC, AuenKr commented
@hkirat 

@manuarora700 asked for this feature in your resume roasting video
So here it is...

2024-09-14 18:32 UTC, AuenKr commented
@siinghd @devsargam

2024-09-14 18:37 UTC, devsargam commented
Can u implement this beautiful library? https://cmdk.paco.me/

2024-09-14 18:37 UTC, devsargam commented
Other than that pr is good

2024-09-14 18:39 UTC, manuarora700 commented
Shadcn commandk internally uses cmdk package. Might as well use that

On Sun, 15 Sep 2024 at 12:08 AM, Sargam ***@***.***> wrote:

> Other than that pr is good
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/code100x/cms/pull/1205#issuecomment-2351098588>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFRSXFKMBQURMXVJZJSHQ2TZWR7B3AVCNFSM6AAAAABODBC7IOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJRGA4TQNJYHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-15 18:24 UTC, AuenKr commented
@devsargam added shadcn commandk component

2024-09-19 15:30 UTC, AuenKr commented
@devsargam any other feedback?

2024-09-19 15:31 UTC, devsargam commented
Let me check this pr by eod

2024-09-23 02:54 UTC, AuenKr commented
> Let me check this pr by eod 


![mr-bean-mrbean.gif](https://github.com/user-attachments/assets/ce99f490-99ba-4ef8-aa91-9d04a4a3636d)

2024-09-23 16:19 UTC, devsargam commented
lol sorry sir

2024-09-23 21:15 UTC, devsargam requested changes

2024-09-23 21:15 UTC, devsargam commented on src/components/search/SearchBar.tsx
> +          if (event.ctrlKey) {
You are just checking with ctrl key but as the name suggests it should also support `⌘K` on mac

2024-09-23 21:18 UTC, devsargam commented on src/components/search/SearchBar.tsx
> +          if (event.ctrlKey) {
```suggestion
          if (event.ctrlKey || e.metaKey) {
```

2024-09-23 21:20 UTC, devsargam requested changes

2024-09-23 21:20 UTC, devsargam commented on src/components/search/SearchBar.tsx
> +          if (event.ctrlKey || e.metaKey) {
```suggestion
          if (event.ctrlKey || event.metaKey) {
```

2024-09-23 21:23 UTC, devsargam requested changes
You probably forgot to add `package.json`

2024-09-25 12:40 UTC, devsargam commented
can u flix conflicts @AuenKr?

2024-09-26 20:21 UTC, AuenKr commented
@devsargam resolves the conflict.
But seems like #1270 is also adding this with other features also.

2024-09-28 17:58 UTC, AuenKr commented
@devsargam, any other change required?

2024-09-28 18:14 UTC, devsargam commented
Let me rereview it

2024-10-02 22:11 UTC, AuenKr commented
@devsargam ??

2024-10-02 22:12 UTC, devsargam commented
yeah yeah it's all good https://github.com/code100x/cms/pull/1270 just want to see what's this got

2024-10-02 22:18 UTC, AuenKr commented
@devsargam 
Do we need to change the user password from cms directly?
I made a PR earlier, but I don't understand why it was not continued.

#749

Shall I add this feature to the current codebase?

2024-10-04 22:17 UTC, merged

2024-10-04 22:17 UTC, devsargam commented
Thank u