feat: Added cms-mobile login route
code100x/cms pull request #1303
Opened 2024-09-22 15:00 UTC by ItsFlash10

2024-09-23 21:56 UTC, devsargam commented
@ItsFlash10 is it done?

2024-09-25 22:39 UTC, devsargam commented
LMK when it's ready to review

2024-10-08 22:10 UTC, ItsFlash10 commented
> @ItsFlash10 are u still working on the mobile app?

@rishavvajpayee will follow up on any comments in this PR

2024-10-19 17:54 UTC, SujithThirumalaisamy requested changes

2024-10-19 17:54 UTC, SujithThirumalaisamy commented on src/app/api/mobile/courses/[courseId]/[collectionId]/[contentId]/route.ts
> +        id: parseInt(contentId, 10),
missed check for if a user has purchased that course or not

2024-10-20 18:13 UTC, devsargam requested changes

2024-10-20 18:13 UTC, devsargam commented on src/app/api/mobile/courses/[courseId]/[collectionId]/[contentId]/route.ts
> +    const contents = await db.content.findUnique({
We are already making a db call for finding if the user has the course access or not. Why don't we reuse the query and get the contents from there itself?

https://github.com/code100x/cms/blob/45668f675f430bb0eb6c8490f6a9d76bd397c997/src/app/api/mobile/courses/%5BcourseId%5D/%5BcollectionId%5D/%5BcontentId%5D/route.ts#L4-L22

2024-10-20 18:13 UTC, devsargam commented on src/app/api/mobile/courses/[courseId]/[collectionId]/route.ts
> +    const collectionData = await db.content.findMany({
Same as above

2024-10-20 18:13 UTC, devsargam commented on src/app/api/mobile/courses/[courseId]/route.ts
> +    const folderContents = await db.content.findMany({
Save as above

2024-10-24 21:05 UTC, merged