fix: Add Picture-in-Picture functionality to video player
code100x/cms pull request #1306
Opened 2024-09-23 11:11 UTC by gupta-soham

### PR Fixes:
- Implements Picture-in-Picture (PiP) mode for the video player
- Introduces `P` key shortcut for quick PiP mode toggle
- Expands playback rate options to include 2.5x and 3x speeds

Resolves #1295 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

## Preview

https://github.com/user-attachments/assets/135bfa2c-7bfc-40aa-a1e0-f23c2e20ca07

2024-09-23 11:11 UTC, gupta-soham commented
@hkirat @siinghd @devsargam 
Please have a look and review this PR.

2024-09-23 21:55 UTC, devsargam requested changes

2024-09-23 21:55 UTC, devsargam commented on src/components/VideoPlayer2.tsx
> +          playbackRates: [0.5, 1, 1.25, 1.5, 1.75, 2, 2.5, 3],
can u remove 2.5 and 3 playback speed?

2024-09-23 21:55 UTC, devsargam commented on src/components/VideoPlayer2.tsx
> +const PLAYBACK_RATES: number[] = [0.5, 1, 1.25, 1.5, 1.75, 2, 2.5, 3];
same as above

2024-10-04 21:44 UTC, merged

2024-10-04 21:44 UTC, devsargam commented
Thank you sir