Update CommentDeleteForm.tsx
code100x/cms pull request #132
Opened 2024-02-29 06:16 UTC by Aryam2121

Destructuring the props directly in the function parameter Destructuring 'execute' from 'useAction'
 Using arrow function for better consistency
Passing an object directly to 'execute'
Explicitly specifying the button type as 'submit'

2024-03-01 05:28 UTC, hkirat commented on src/components/comment/CommentDeleteForm.tsx
> +  // Using 'const' for variables that don't change
no need for this comment

2024-03-01 05:28 UTC, hkirat requested changes

2024-03-01 06:08 UTC, Aryam2121 commented on src/components/comment/CommentDeleteForm.tsx
> +  // Using 'const' for variables that don't change
ok sir so my code is not relevant ?

2024-03-01 06:10 UTC, Aryam2121 commented on src/components/comment/CommentDeleteForm.tsx
> +  // Destructuring 'execute' from 'useAction'
ok sir my mistake

2024-03-01 12:14 UTC, Aryam2121 commented on src/components/comment/CommentDeleteForm.tsx
> +  // Using 'const' for variables that don't change
ok sir

2024-03-06 18:03 UTC, hkirat commented
Closing for now, please reopen after issues have been resolved

2024-03-06 18:03 UTC, closed without merging