refactor(comment): improve voting functionality
code100x/cms pull request #1323
Opened 2024-09-25 14:49 UTC by NawinKumarSharma

### PR Fixes:
- 1  #1320
- 2  #1322

Resolves  #1322  #1320

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

2024-09-25 22:04 UTC, devsargam requested changes
19 files changed. Can u reduce lint diffs?

2024-09-26 09:28 UTC, NawinKumarSharma commented
@devsargam  fixed the lint diff!

2024-10-03 12:40 UTC, devsargam approved these changes

2024-10-03 12:40 UTC, merged

2024-10-03 12:40 UTC, devsargam commented
Thank you sir