feat: to navigate through videos by prev and next video button
code100x/cms pull request #1456
Opened 2024-10-08 04:06 UTC by Prashant-flick

### PR Features:
- Added functionality to navigate through videos within a course using previous and next buttons.
- Automatically plays the next video in the course after the current video ends.

Limitations
- Navigation to the next course after the last video in the current course is not implemented.
- Navigation is limited to videos only, excluding notes.

https://github.com/user-attachments/assets/47436014-6c33-4714-ae3a-4eef288395d8

Resolves #1166

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

2024-10-08 21:04 UTC, devsargam commented
adding it to things to review

2024-10-12 13:14 UTC, Prashant-flick commented
hey @devsargam 
your thoughts on this?

2024-10-12 13:20 UTC, devsargam commented
This is great but I need to review for all edge cases

2024-10-20 20:39 UTC, devsargam requested changes

2024-10-23 05:03 UTC, Prashant-flick commented on src/components/VideoPlayer2.tsx
> +    root.render(<span className="material-symbols-outlined">picture_in_picture_alt</span>);
there was some error on prev logic, and also some error on my logic.
i have fixed all the errors, please review it.

2024-11-17 13:33 UTC, devsargam commented
Sorry this looks really good but considering this pr
ref: https://github.com/code100x/cms/pull/1434

2024-11-17 13:33 UTC, closed without merging