Added scroll up button in notes
code100x/cms pull request #1483
Opened 2024-10-16 10:07 UTC by rohhann12

### PR Fixes:
- 1. Added a scroll up button in notes so that the user doesn't have to keep scrolling up after he/she have read through them,
added video to show how efficient is for the user to scroll back up to `Show Content` button

fix-
https://github.com/user-attachments/assets/6de52f02-aa53-46c1-9954-a19e83218749

*tried to solve this using script from next/script and not using hooks to avoid usage of "use client"

Resolves #[Issue Number if there] 

### Checklist before requesting a review
- [] I have performed a self-review of my code
- [] I assure there is no similar/duplicate pull request regarding same issue

2024-10-16 10:08 UTC, rohhann12 commented on src/components/comment/Comments.tsx
> +            className={`text-xl font-bold taracking-tighter text-primary md:text-2xl`}
used gpt to format it correctly, dont know why it changed this, changing

2024-10-20 19:00 UTC, devsargam requested changes

2024-10-20 19:00 UTC, devsargam commented on src/components/comment/Comments.tsx
> +          function toggleBackToTopButton() {
Do this function the react way not like this

2024-10-21 05:44 UTC, rohhann12 commented
too clumsy, putting up a new one, with minimal changes

2024-10-21 05:44 UTC, closed without merging