Fix/Feat: comment counters, actions based on role
code100x/cms pull request #170
Opened 2024-03-09 06:38 UTC by siinghd

2024-03-12 06:52 UTC, hkirat requested changes

2024-03-12 15:28 UTC, siinghd commented
@hkirat hi veere, have removed console.log

2024-03-17 07:46 UTC, merged

2024-03-17 07:46 UTC, hkirat commented
/bounty $75

2024-03-17 22:22 UTC, nimit9 commented
Hey @siinghd , I think you missed adding the new migration of 'isPinned' column in Comment Table