fix: #187 - adjusted sidebar height
code100x/cms pull request #206
Opened 2024-03-11 17:12 UTC by prasanth7890

2024-03-11 17:34 UTC, devsargam requested changes

2024-03-11 17:34 UTC, devsargam commented on src/components/Sidebar.tsx
> +     className={`overflow-y-scroll h-[${(window.innerHeight - 64)}px] w-[300px] min-w-[133px] bg-gray-50 dark:bg-gray-800 cursor-pointer sticky top-[64px] self-start w-84`}
pls, use tailwind utility

2024-03-11 17:34 UTC, devsargam commented on src/components/Sidebar.tsx
> +     className={`overflow-y-scroll h-[${(window.innerHeight - 64)}px] w-[300px] min-w-[133px] bg-gray-50 dark:bg-gray-800 cursor-pointer sticky top-[64px] self-start w-84`}
```suggestion
     className="overflow-y-scroll max-w-[calc(100vw-64px)] w-[300px] min-w-[133px] bg-gray-50 dark:bg-gray-800 cursor-pointer sticky top-[64px] self-start w-84"
```

2024-03-11 19:29 UTC, prasanth7890 commented on src/components/Sidebar.tsx
> +     className={`overflow-y-scroll h-[${(window.innerHeight - 64)}px] w-[300px] min-w-[133px] bg-gray-50 dark:bg-gray-800 cursor-pointer sticky top-[64px] self-start w-84`}
updated with suggested changes. please review

2024-03-11 19:32 UTC, devsargam commented on src/components/Sidebar.tsx
> +     className={`overflow-y-scroll h-[${(window.innerHeight - 64)}px] w-[300px] min-w-[133px] bg-gray-50 dark:bg-gray-800 cursor-pointer sticky top-[64px] self-start w-84`}
LGTM

2024-03-11 19:32 UTC, devsargam approved these changes

2024-03-12 06:49 UTC, hkirat commented
please add screenshots/description of the change

2024-03-12 16:09 UTC, prasanth7890 commented
> please add screenshots/description of the change

Hii Harkirat sir, 
i edited the first comment by adding screenshots and changes. once please review. 

Thank you

2024-03-17 07:50 UTC, merged