Used cache in the API calls
code100x/cms pull request #208
Opened 2024-03-11 18:06 UTC by adexh

## Changes

- Added use of the Cache class in the purchase API

2024-03-11 18:57 UTC, hkirat commented on src/utiles/appx.ts
> +  Cache.getInstance().set('courses', [email], responses, 60 * 60 * 24);
only this line and the cache get for this is needed
No need for any LOCAL_CMS_PROVIDER logic that can remain uncached

2024-03-11 18:57 UTC, hkirat requested changes
just one comment

2024-03-12 02:34 UTC, adexh commented
@hkirat Done Sir.
Removed the logic for LOCAL_CMS_PROVIDER and kept its response uncached.

2024-03-12 06:49 UTC, merged

2024-03-12 06:49 UTC, hkirat commented
Thankyou! 
/bounty $15