Added Admin page & some UI fix
code100x/cms pull request #819
Opened 2024-07-10 12:12 UTC by pruthviraj7714

**Added the Admin Page to naviage to Add course and add content in the dropdown. Only Admins Can have it's access**
**Added toast for validation to check if content is added or not, Made UI good & informative**
 
Preview:
https://github.com/code100x/cms/assets/138095461/06092094-c592-4f21-9941-3532c1ae1276

### Checklist before requesting a review
- [✔] I have performed a self-review of my code
- [✔] I assure there is no similar/duplicate pull request regarding same issue

2024-07-10 15:22 UTC, siinghd requested changes
Isnt there already admin page?

2024-07-10 15:22 UTC, siinghd commented on .env.example
> +NEXT_PUBLIC_ADMINS = "Random,example@gmail.com,test@gmail.com"
why this public? we dont need this public as the role is inside session

2024-07-10 15:22 UTC, siinghd commented on src/components/profile-menu/ProfileDropdown.tsx
> +            Isession?.user?.email ?? '',
there is session.user.role

2024-07-10 16:07 UTC, pruthviraj7714 commented
@siinghd done!

2024-07-21 15:43 UTC, pruthviraj7714 commented
@hkirat check out!

2024-07-28 17:03 UTC, closed without merging